apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../manager
- ../../rbac
- nautes_configs.yaml
- controller_manager_log_pvc.yaml

patchesStrategicMerge:
- manager_auth_proxy_patch.yaml
- manager_configs_patch.yaml
- manager_log_persistence_patch.yaml
- third_part_components.yaml
- component_ategory_definition.yaml
- cluster_common_config.yaml