---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: artifactrepoes.nautes.resource.nautes.io
spec:
  group: nautes.resource.nautes.io
  names:
    kind: ArtifactRepo
    listKind: ArtifactRepoList
    plural: artifactrepoes
    singular: artifactrepo
  scope: Namespaced
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: ArtifactRepo is the Schema for the artifactrepoes API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ArtifactRepoSpec defines the desired state of ArtifactRepo
            properties:
              artifactRepoProvider:
                type: string
              packageType:
                description: maven, python, go...
                enum:
                - maven
                - python
                - go
                type: string
              product:
                type: string
              projects:
                items:
                  type: string
                nullable: true
                type: array
              repoName:
                type: string
              repoType:
                description: remote, local, virtual...
                enum:
                - remote
                - local
                - virtual
                type: string
            required:
            - artifactRepoProvider
            - packageType
            - product
            - repoName
            - repoType
            type: object
          status:
            description: ArtifactRepoStatus defines the observed state of ArtifactRepo
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
