---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.11.3
  creationTimestamp: null
  name: environments.nautes.resource.nautes.io
spec:
  group: nautes.resource.nautes.io
  names:
    kind: Environment
    listKind: EnvironmentList
    plural: environments
    singular: environment
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .spec.product
      name: PRODUCTRESOURCENAME
      type: string
    - jsonPath: .spec.cluster
      name: CLUSTER
      type: string
    - jsonPath: .spec.envType
      name: ENVTYPE
      type: string
    name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Environment is the Schema for the environments API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: EnvironmentSpec defines the desired state of Environment
            properties:
              cluster:
                type: string
              envType:
                type: string
              product:
                type: string
            required:
            - cluster
            - envType
            - product
            type: object
          status:
            description: EnvironmentStatus defines the observed state of Environment
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
